name: My Shoreditch
favicon: null
layout_spectrum: 1
typography_spectrum: 0.48776
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
title: My ShoreditchNews - Culture - Pictures
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a52b3c'
    - '#c25f6d'
    - '#ffd8d2'
    - '#d7838d'
    - '#68202d'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
